### ISSUE TITLE
Thanks <3

### ISSUE THREAD

**Issue by Dolu1990** [CodeImp/sblkdev#2]

**Comment by CodeImp** [comment]
This example could already be outdated.
See: [https://github.com/veeam/blksnap/blob/master/module/snapimage.c](https://github.com/veeam/blksnap/blob/master/module/snapimage.c)

**Comment by Dolu1990** [comment]
I did tested your one on linux 5.10.1, it seems fine so far :)
I'm planning to modify it a bit, in order to have a very simple low level block device that i could use in a hardware cpu simulation (https://github.com/SpinalHDL/NaxRiscv) to boot debian (can't use a ramfs anymore at that stage XD)

**Comment by Dolu1990** [comment]
Got this repo code to work on linux 5.14.0 via a small change : 

```c
  //alloc_disk => blk_alloc_disk
 struct gendisk *disk = blk_alloc_disk(NUMA_NO_NODE); //only one partition 
 
disk->first_minor = 0;
+disk->minors = 1;
```
